version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
  orchestrator:
    build:
      context: ./
      dockerfile: ./orchestrator/Dockerfile
    ports:
      - 8081:5000
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/orchestrator/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./orchestrator/src:/app/orchestrator/src
  fraud_detection:
    build:
      context: ./
      dockerfile: ./fraud_detection/Dockerfile
    ports:
      - 50051:50051
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/fraud_detection/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./fraud_detection/src:/app/fraud_detection/src
  transaction_verification:
    build:
      context: ./
      dockerfile: ./transaction_verification/Dockerfile
    ports:
      - 50052:50052
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/transaction_verification/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./transaction_verification/src:/app/transaction_verification/src
  suggestions:
    build:
      # Use the current directory as the build context
      # This allows us to access the files in the current directory inside the Dockerfile
      context: ./
      # Use the Dockerfile in the transaction_verification directorys
      dockerfile: ./suggestions/Dockerfile
    ports:
      # Expose port 50051 on the host, and map port 50051 of the container to port 50051 on the host
      - 50053:50053
    environment:
      # Pass the environment variables to the container
      # The PYTHONUNBUFFERED environment variable ensures that the output from the application is logged to the console
      - PYTHONUNBUFFERED=TRUE
      # The PYTHONFILE environment variable specifies the absolute entry point of the application
      # Check app.py in the transaction_verification directory to see how this is used
      - PYTHONFILE=/app/suggestions/src/app.py
    volumes:
      # Mount the utils directory in the current directory to the /app/utils directory in the container
      - ./utils:/app/utils
      # Mount the transaction_verification/src directory in the current directory to the /app/transaction_verification/src directory in the container
      - ./suggestions/src:/app/suggestions/src
  order_queue:
    build:
      context: ./
      dockerfile: ./order_queue/Dockerfile
    ports:
      - 50054:50054
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/order_queue/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./order_queue/src:/app/order_queue/src
  order_executor_1:
    build:
      context: ./
      dockerfile: ./order_executor/Dockerfile
    ports:
      - 50055:50055
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/order_executor/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./order_executor/src:/app/order_executor/src
  order_executor_2:
    build:
      context: ./
      dockerfile: ./order_executor/Dockerfile
    ports:
      - 50056:50055
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/order_executor/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./order_executor/src:/app/order_executor/src
  books_database_1:
    build:
      context: ./
      dockerfile: ./books_database_1/Dockerfile
    ports:
      - 50057:50057
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/books_database_1/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./books_database_1/src:/app/books_database_1/src
  books_database_2:
    build:
      context: ./
      dockerfile: ./books_database_2/Dockerfile
    ports:
      - 50058:50058
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/books_database_2/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./books_database_2/src:/app/books_database_2/src
  books_database_3:
    build:
      context: ./
      dockerfile: ./books_database_3/Dockerfile
    ports:
      - 50059:50059
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/books_database_3/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./books_database_3/src:/app/books_database_3/src
  payment_system:
    build:
      context: ./
      dockerfile: ./payment_system/Dockerfile
    ports:
      - 50060:50060
    environment:
      - PYTHONUNBUFFERED=TRUE
      - PYTHONFILE=/app/payment_system/src/app.py
    volumes:
      - ./utils:/app/utils
      - ./payment_system/src:/app/payment_system/src
  consul:
    image: consul:1.10.4
    command: agent -dev -client 0.0.0.0
    ports:
      - "8500:8500"