# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fraud_detection/fraud_detection.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%fraud_detection/fraud_detection.proto\x12\x0f\x66raud_detection\"\xd3\x01\n\x15\x46raudDetectionRequest\x12#\n\x04user\x18\x01 \x01(\x0b\x32\x15.fraud_detection.User\x12/\n\ncreditCard\x18\x02 \x01(\x0b\x32\x1b.fraud_detection.CreditCard\x12\x30\n\x0e\x62illingAddress\x18\x03 \x01(\x0b\x32\x18.fraud_detection.Address\x12\x32\n\x0cvector_clock\x18\x04 \x01(\x0b\x32\x1c.fraud_detection.VectorClock\"\x82\x01\n\x0bVectorClock\x12@\n\ntimestamps\x18\x01 \x03(\x0b\x32,.fraud_detection.VectorClock.TimestampsEntry\x1a\x31\n\x0fTimestampsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"%\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x02 \x01(\t\"A\n\nCreditCard\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"T\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\"r\n\x16\x46raudDetectionResponse\x12\x14\n\x0cisFraudulent\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x32\n\x0cvector_clock\x18\x03 \x01(\x0b\x32\x1c.fraud_detection.VectorClock2w\n\x15\x46raudDetectionService\x12^\n\x0b\x44\x65tectFraud\x12&.fraud_detection.FraudDetectionRequest\x1a\'.fraud_detection.FraudDetectionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection.fraud_detection_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VECTORCLOCK_TIMESTAMPSENTRY']._options = None
  _globals['_VECTORCLOCK_TIMESTAMPSENTRY']._serialized_options = b'8\001'
  _globals['_FRAUDDETECTIONREQUEST']._serialized_start=59
  _globals['_FRAUDDETECTIONREQUEST']._serialized_end=270
  _globals['_VECTORCLOCK']._serialized_start=273
  _globals['_VECTORCLOCK']._serialized_end=403
  _globals['_VECTORCLOCK_TIMESTAMPSENTRY']._serialized_start=354
  _globals['_VECTORCLOCK_TIMESTAMPSENTRY']._serialized_end=403
  _globals['_USER']._serialized_start=405
  _globals['_USER']._serialized_end=442
  _globals['_CREDITCARD']._serialized_start=444
  _globals['_CREDITCARD']._serialized_end=509
  _globals['_ADDRESS']._serialized_start=511
  _globals['_ADDRESS']._serialized_end=595
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_start=597
  _globals['_FRAUDDETECTIONRESPONSE']._serialized_end=711
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=713
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=832
# @@protoc_insertion_point(module_scope)
