# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment_system/payment_system.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#payment_system/payment_system.proto\x12\x0epayment_system\"A\n\nCreditCard\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"O\n\x13\x43heckBalanceRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\x12(\n\x04\x63\x61rd\x18\x02 \x01(\x0b\x32\x1a.payment_system.CreditCard\"\'\n\x14\x43heckBalanceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"Q\n\x15\x43onfirmPaymentRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\x12(\n\x04\x63\x61rd\x18\x02 \x01(\x0b\x32\x1a.payment_system.CreditCard\")\n\x16\x43onfirmPaymentResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xcc\x01\n\x0ePaymentService\x12Y\n\x0c\x43heckBalance\x12#.payment_system.CheckBalanceRequest\x1a$.payment_system.CheckBalanceResponse\x12_\n\x0e\x43onfirmPayment\x12%.payment_system.ConfirmPaymentRequest\x1a&.payment_system.ConfirmPaymentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_system.payment_system_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CREDITCARD']._serialized_start=55
  _globals['_CREDITCARD']._serialized_end=120
  _globals['_CHECKBALANCEREQUEST']._serialized_start=122
  _globals['_CHECKBALANCEREQUEST']._serialized_end=201
  _globals['_CHECKBALANCERESPONSE']._serialized_start=203
  _globals['_CHECKBALANCERESPONSE']._serialized_end=242
  _globals['_CONFIRMPAYMENTREQUEST']._serialized_start=244
  _globals['_CONFIRMPAYMENTREQUEST']._serialized_end=325
  _globals['_CONFIRMPAYMENTRESPONSE']._serialized_start=327
  _globals['_CONFIRMPAYMENTRESPONSE']._serialized_end=368
  _globals['_PAYMENTSERVICE']._serialized_start=371
  _globals['_PAYMENTSERVICE']._serialized_end=575
# @@protoc_insertion_point(module_scope)
