# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_queue/order_queue.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dorder_queue/order_queue.proto\x12\norderqueue\"%\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontact\x18\x02 \x01(\t\"A\n\nCreditCard\x12\x0e\n\x06number\x18\x01 \x01(\t\x12\x16\n\x0e\x65xpirationDate\x18\x02 \x01(\t\x12\x0b\n\x03\x63vv\x18\x03 \x01(\t\"&\n\x04Item\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"[\n\x0e\x42illingAddress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\"\xc4\x01\n\x0cOrderRequest\x12\x1e\n\x04user\x18\x01 \x01(\x0b\x32\x10.orderqueue.User\x12*\n\ncreditCard\x18\x02 \x01(\x0b\x32\x16.orderqueue.CreditCard\x12\x13\n\x0buserComment\x18\x03 \x01(\t\x12\x1f\n\x05items\x18\x04 \x03(\x0b\x32\x10.orderqueue.Item\x12\x32\n\x0e\x62illingAddress\x18\x05 \x01(\x0b\x32\x1a.orderqueue.BillingAddress\"3\n\x0f\x45nqueueResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2Z\n\x11OrderQueueService\x12\x45\n\x0c\x45nqueueOrder\x12\x18.orderqueue.OrderRequest\x1a\x1b.orderqueue.EnqueueResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'order_queue.order_queue_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USER']._serialized_start=45
  _globals['_USER']._serialized_end=82
  _globals['_CREDITCARD']._serialized_start=84
  _globals['_CREDITCARD']._serialized_end=149
  _globals['_ITEM']._serialized_start=151
  _globals['_ITEM']._serialized_end=189
  _globals['_BILLINGADDRESS']._serialized_start=191
  _globals['_BILLINGADDRESS']._serialized_end=282
  _globals['_ORDERREQUEST']._serialized_start=285
  _globals['_ORDERREQUEST']._serialized_end=481
  _globals['_ENQUEUERESPONSE']._serialized_start=483
  _globals['_ENQUEUERESPONSE']._serialized_end=534
  _globals['_ORDERQUEUESERVICE']._serialized_start=536
  _globals['_ORDERQUEUESERVICE']._serialized_end=626
# @@protoc_insertion_point(module_scope)
